<?php
declare(strict_types=1);
use App\Core\Support;
use App\Core\Ui;

/** @var array $media_row @var bool $referenced @var list<array> $posts @var bool $thumbnail */
$media = $media_row;
?>
<div class="page-head">
    <div class="page-head__text">
        <h1><?= Support::e((string) $media['original_name']) ?></h1>
        <p class="page-head__sub">
            <?= Support::e((string) $media['kind']) ?> ·
            <?= Support::e(Support::bytesToHuman((int) $media['size_bytes'])) ?> ·
            uploaded <?= Support::e(Ui::ago((string) $media['created_at'])) ?>
        </p>
    </div>
    <div class="page-head__actions">
        <a class="btn btn--primary" href="/posts/new?media=<?= (int) $media['id'] ?>&kind=<?= $media['kind'] === 'VIDEO' ? 'VIDEO' : 'IMAGE' ?>">
            <?= Ui::icon('plus', 16) ?> Compose with this file
        </a>
        <a class="btn" href="/media"><?= Ui::icon('x', 16) ?> Back</a>
    </div>
</div>

<div class="grid grid--sidebar">
    <section class="card">
        <div class="card__head"><h2>Preview</h2></div>
        <div class="card__body">
            <?php if ((string) $media['kind'] === 'IMAGE'): ?>
                <img src="/media/<?= (int) $media['id'] ?>/file" alt=""
                     style="max-width:100%;border-radius:8px;border:1px solid var(--border)">
            <?php else: ?>
                <video controls preload="metadata" style="width:100%;border-radius:8px;background:#000"
                       src="/media/<?= (int) $media['id'] ?>/file"></video>
                <?php if ($thumbnail): ?>
                    <p class="small muted mt-1">A poster frame was generated by FFmpeg.</p>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </section>

    <div class="stack">
        <section class="card">
            <div class="card__head"><h2>FFmpeg inspection</h2></div>
            <div class="card__body">
                <dl class="kv">
                    <dt>Resolution</dt>
                    <dd><?= $media['width'] !== null ? (int) $media['width'] . ' × ' . (int) $media['height'] : '—' ?></dd>
                    <dt>Aspect ratio</dt><dd><?= Support::e((string) ($media['aspect_ratio'] ?? '—')) ?></dd>
                    <dt>Duration</dt><dd><?= Support::e(Ui::duration($media['duration_s'] !== null ? (float) $media['duration_s'] : null)) ?></dd>
                    <dt>Frame rate</dt><dd><?= $media['fps'] !== null ? Support::e(rtrim(rtrim(number_format((float) $media['fps'], 3), '0'), '.')) . ' fps' : '—' ?></dd>
                    <dt>Codec</dt><dd><?= Support::e((string) ($media['codec'] ?? '—')) ?></dd>
                    <dt>MIME type</dt><dd class="mono small"><?= Support::e((string) $media['mime_type']) ?></dd>
                    <dt>SHA-256</dt><dd class="mono tiny" style="word-break:break-all"><?= Support::e((string) ($media['checksum_sha256'] ?? '—')) ?></dd>
                    <dt>Probe status</dt><dd><?= Ui::status((string) $media['probe_status']) ?></dd>
                    <dt>Storage strategy</dt><dd><?= Support::e((string) $media['strategy']) ?></dd>
                    <dt>Storage key</dt><dd class="mono tiny"><?= Support::e((string) $media['relative_path']) ?></dd>
                </dl>
                <?php if (!empty($media['probe_error'])): ?>
                    <div class="alert alert--warn mt-2">
                        <?= Ui::icon('alert', 16) ?>
                        <div class="small"><?= Support::e((string) $media['probe_error']) ?></div>
                    </div>
                <?php endif; ?>
            </div>
        </section>

        <section class="card">
            <div class="card__head"><h2>Used by</h2></div>
            <div class="card__body">
                <?php if ($posts === []): ?>
                    <p class="muted small mb-0">Not attached to any post yet.</p>
                <?php else: ?>
                    <ul class="stack" style="list-style:none;margin:0;padding:0">
                        <?php foreach ($posts as $post): ?>
                            <li class="row row--between">
                                <a class="small" href="/posts/<?= (int) $post['id'] ?>">
                                    <?= Support::e(Support::excerpt((string) $post['caption'], 46)) ?>
                                </a>
                                <?= Ui::status((string) $post['status']) ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>

                <hr class="hr">
                <?php if ($referenced): ?>
                    <div class="alert alert--warn">
                        <?= Ui::icon('alert', 16) ?>
                        <div class="small">This file is referenced by live work or a draft, so it cannot be deleted yet.</div>
                    </div>
                <?php else: ?>
                    <button class="btn btn--danger btn--block"
                            data-action="/media/<?= (int) $media['id'] ?>/remove"
                            data-confirm="Delete this file? It is removed from storage once no job references it."
                            data-reload="true"
                            data-success="Media scheduled for deletion.">
                        <?= Ui::icon('trash', 16) ?> Delete file
                    </button>
                <?php endif; ?>
            </div>
        </section>
    </div>
</div>
